export const quotes = [
  {
    q: "Some people don't like change, but you need to embrace change if the alternative is disaster.",
    a: "Elon Musk",
    c: "93",
    h: "<blockquote>&ldquo;Some people don't like change, but you need to embrace change if the alternative is disaster.&rdquo; &mdash; <footer>Elon Musk</footer></blockquote>",
  },
  {
    q: "Hope is important because it can make the present moment less difficult to bear. If we believe that tomorrow will be better, we can bear a hardship today.",
    a: "Thich Nhat Hanh",
    c: "154",
    h: "<blockquote>&ldquo;Hope is important because it can make the present moment less difficult to bear. If we believe that tomorrow will be better, we can bear a hardship today.&rdquo; &mdash; <footer>Thich Nhat Hanh</footer></blockquote>",
  },
  {
    q: "The best of us sometimes eat our words. ",
    a: "Albus Dumbledore",
    c: "41",
    h: "<blockquote>&ldquo;The best of us sometimes eat our words. &rdquo; &mdash; <footer>Albus Dumbledore</footer></blockquote>",
  },
  {
    q: "My powers are ordinary. Only my application brings me success.",
    a: "Isaac Newton",
    c: "62",
    h: "<blockquote>&ldquo;My powers are ordinary. Only my application brings me success.&rdquo; &mdash; <footer>Isaac Newton</footer></blockquote>",
  },
  {
    q: "The eyes of others our prisons; their thoughts our cages.",
    a: "Virginia Woolf",
    c: "57",
    h: "<blockquote>&ldquo;The eyes of others our prisons; their thoughts our cages.&rdquo; &mdash; <footer>Virginia Woolf</footer></blockquote>",
  },
  {
    q: "Your world is a living expression of how you are using and have used your mind.",
    a: "Earl Nightingale",
    c: "79",
    h: "<blockquote>&ldquo;Your world is a living expression of how you are using and have used your mind.&rdquo; &mdash; <footer>Earl Nightingale</footer></blockquote>",
  },
  {
    q: "The important thing is not what one is born with but what use one makes of that equipment.",
    a: "Alfred Adler",
    c: "90",
    h: "<blockquote>&ldquo;The important thing is not what one is born with but what use one makes of that equipment.&rdquo; &mdash; <footer>Alfred Adler</footer></blockquote>",
  },
  {
    q: "An ounce of performance is worth pounds of promises.",
    a: "Mae West",
    c: "52",
    h: "<blockquote>&ldquo;An ounce of performance is worth pounds of promises.&rdquo; &mdash; <footer>Mae West</footer></blockquote>",
  },
  {
    q: "You cannot change your destination overnight but you can change your direction overnight.",
    a: "Jim Rohn",
    c: "89",
    h: "<blockquote>&ldquo;You cannot change your destination overnight but you can change your direction overnight.&rdquo; &mdash; <footer>Jim Rohn</footer></blockquote>",
  },
  {
    q: "If you want others to be happy, practice compassion. If you want to be happy, practice compassion.",
    a: "Dalai Lama",
    c: "98",
    h: "<blockquote>&ldquo;If you want others to be happy, practice compassion. If you want to be happy, practice compassion.&rdquo; &mdash; <footer>Dalai Lama</footer></blockquote>",
  },
  {
    q: "You can't stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes.",
    a: "A.A. Milne",
    c: "112",
    h: "<blockquote>&ldquo;You can't stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes.&rdquo; &mdash; <footer>A.A. Milne</footer></blockquote>",
  },
  {
    q: "Continuous effort - not strength or intelligence - is the key to unlocking our potential.",
    a: "Winston Churchill",
    c: "89",
    h: "<blockquote>&ldquo;Continuous effort - not strength or intelligence - is the key to unlocking our potential.&rdquo; &mdash; <footer>Winston Churchill</footer></blockquote>",
  },
  {
    q: "We ourselves feel that what we are doing is just a drop in the ocean. But the ocean would be less because of that missing drop.",
    a: "Mother Teresa",
    c: "127",
    h: "<blockquote>&ldquo;We ourselves feel that what we are doing is just a drop in the ocean. But the ocean would be less because of that missing drop.&rdquo; &mdash; <footer>Mother Teresa</footer></blockquote>",
  },
  {
    q: "A dream you dream alone is only a dream. A dream you dream together is reality.",
    a: "Yoko Ono",
    c: "79",
    h: "<blockquote>&ldquo;A dream you dream alone is only a dream. A dream you dream together is reality.&rdquo; &mdash; <footer>Yoko Ono</footer></blockquote>",
  },
  {
    q: "Success is doing what you want to do, when you want, where you want, with whom you want, as much as you want.",
    a: "Tony Robbins",
    c: "109",
    h: "<blockquote>&ldquo;Success is doing what you want to do, when you want, where you want, with whom you want, as much as you want.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
  },
  {
    q: "We must cultivate our garden. ",
    a: "Voltaire",
    c: "30",
    h: "<blockquote>&ldquo;We must cultivate our garden. &rdquo; &mdash; <footer>Voltaire</footer></blockquote>",
  },
  {
    q: "When we think about our strengths, we are strong. When we think about our weaknesses, we are weak.",
    a: "Peter A. Cohen",
    c: "98",
    h: "<blockquote>&ldquo;When we think about our strengths, we are strong. When we think about our weaknesses, we are weak.&rdquo; &mdash; <footer>Peter A. Cohen</footer></blockquote>",
  },
  {
    q: "Confidence breeds beauty. ",
    a: "Estee Lauder",
    c: "27",
    h: "<blockquote>&ldquo;Confidence breeds beauty. &rdquo; &mdash; <footer>Estee Lauder</footer></blockquote>",
  },
  {
    q: "Better to die fighting for freedom than be a prisoner all the days of your life.",
    a: "Bob Marley",
    c: "80",
    h: "<blockquote>&ldquo;Better to die fighting for freedom than be a prisoner all the days of your life.&rdquo; &mdash; <footer>Bob Marley</footer></blockquote>",
  },
  {
    q: "Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.",
    a: "Sun Tzu",
    c: "110",
    h: "<blockquote>&ldquo;Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.&rdquo; &mdash; <footer>Sun Tzu</footer></blockquote>",
  },
  {
    q: "With the new day comes new strength and new thoughts.",
    a: "Eleanor Roosevelt",
    c: "53",
    h: "<blockquote>&ldquo;With the new day comes new strength and new thoughts.&rdquo; &mdash; <footer>Eleanor Roosevelt</footer></blockquote>",
  },
  {
    q: "I learned the value of hard work by working hard. ",
    a: "Margaret Mead",
    c: "50",
    h: "<blockquote>&ldquo;I learned the value of hard work by working hard. &rdquo; &mdash; <footer>Margaret Mead</footer></blockquote>",
  },
  {
    q: "Inspiration exists, but it has to find you working.",
    a: "Pablo Picasso",
    c: "51",
    h: "<blockquote>&ldquo;Inspiration exists, but it has to find you working.&rdquo; &mdash; <footer>Pablo Picasso</footer></blockquote>",
  },
  {
    q: "Ask no questions, and you'll be told no lies.",
    a: "Charles Dickens",
    c: "45",
    h: "<blockquote>&ldquo;Ask no questions, and you'll be told no lies.&rdquo; &mdash; <footer>Charles Dickens</footer></blockquote>",
  },
  {
    q: "Coming together is a beginning, staying together is progress, and working together is success. ",
    a: "Henry Ford",
    c: "95",
    h: "<blockquote>&ldquo;Coming together is a beginning, staying together is progress, and working together is success. &rdquo; &mdash; <footer>Henry Ford</footer></blockquote>",
  },
  {
    q: "All men who have achieved great things have been great dreamers. ",
    a: "Orison Swett Marden",
    c: "65",
    h: "<blockquote>&ldquo;All men who have achieved great things have been great dreamers. &rdquo; &mdash; <footer>Orison Swett Marden</footer></blockquote>",
  },
  {
    q: "Resentment or grudges do no harm to the person against whom you hold these feelings but every day and every night of your life, they are eating at you.",
    a: "Norman Vincent Peale",
    c: "151",
    h: "<blockquote>&ldquo;Resentment or grudges do no harm to the person against whom you hold these feelings but every day and every night of your life, they are eating at you.&rdquo; &mdash; <footer>Norman Vincent Peale</footer></blockquote>",
  },
  {
    q: "Inspire yourself to be great. Being good isn't good enough.",
    a: "Gurbaksh Chahal",
    c: "59",
    h: "<blockquote>&ldquo;Inspire yourself to be great. Being good isn't good enough.&rdquo; &mdash; <footer>Gurbaksh Chahal</footer></blockquote>",
  },
  {
    q: "Problems remain as problems because people are busy defending them rather than finding solutions.",
    a: "Celestine Chua",
    c: "97",
    h: "<blockquote>&ldquo;Problems remain as problems because people are busy defending them rather than finding solutions.&rdquo; &mdash; <footer>Celestine Chua</footer></blockquote>",
  },
  {
    q: "A person hears only what they understand.",
    a: "Johann Wolfgang von Goethe",
    c: "41",
    h: "<blockquote>&ldquo;A person hears only what they understand.&rdquo; &mdash; <footer>Johann Wolfgang von Goethe</footer></blockquote>",
  },
  {
    q: "I like the dreams of the future better than the history of the past.",
    a: "Thomas Jefferson",
    c: "68",
    h: "<blockquote>&ldquo;I like the dreams of the future better than the history of the past.&rdquo; &mdash; <footer>Thomas Jefferson</footer></blockquote>",
  },
  {
    q: "Don't talk about what you have done or what you are going to do.",
    a: "Thomas Jefferson",
    c: "64",
    h: "<blockquote>&ldquo;Don't talk about what you have done or what you are going to do.&rdquo; &mdash; <footer>Thomas Jefferson</footer></blockquote>",
  },
  {
    q: "Life is one long process of getting tired.",
    a: "Samuel Butler",
    c: "42",
    h: "<blockquote>&ldquo;Life is one long process of getting tired.&rdquo; &mdash; <footer>Samuel Butler</footer></blockquote>",
  },
  {
    q: "It is secondary whether we choose belief or defiance. What is precious is that we are always able to choose.",
    a: "Ming-Dao Deng",
    c: "108",
    h: "<blockquote>&ldquo;It is secondary whether we choose belief or defiance. What is precious is that we are always able to choose.&rdquo; &mdash; <footer>Ming-Dao Deng</footer></blockquote>",
  },
  {
    q: "Faithless is he that says farewell when the road darkens.",
    a: "J.R.R. Tolkien",
    c: "57",
    h: "<blockquote>&ldquo;Faithless is he that says farewell when the road darkens.&rdquo; &mdash; <footer>J.R.R. Tolkien</footer></blockquote>",
  },
  {
    q: "The most virtuous are those who content themselves with being virtuous without seeking to appear so.",
    a: "Plato",
    c: "100",
    h: "<blockquote>&ldquo;The most virtuous are those who content themselves with being virtuous without seeking to appear so.&rdquo; &mdash; <footer>Plato</footer></blockquote>",
  },
  {
    q: "By perseverance the snail reached the ark.",
    a: "Charles Spurgeon",
    c: "42",
    h: "<blockquote>&ldquo;By perseverance the snail reached the ark.&rdquo; &mdash; <footer>Charles Spurgeon</footer></blockquote>",
  },
  {
    q: "The quality of your commitments will determine the course of your life.",
    a: "Ralph Marston",
    c: "71",
    h: "<blockquote>&ldquo;The quality of your commitments will determine the course of your life.&rdquo; &mdash; <footer>Ralph Marston</footer></blockquote>",
  },
  {
    q: "I thought how unpleasant it is to be locked out; and I thought how it is worse, perhaps, to be locked in.",
    a: "Virginia Woolf",
    c: "105",
    h: "<blockquote>&ldquo;I thought how unpleasant it is to be locked out; and I thought how it is worse, perhaps, to be locked in.&rdquo; &mdash; <footer>Virginia Woolf</footer></blockquote>",
  },
  {
    q: "A poet should be so crafty with words that he is envied even for his pains.",
    a: "Criss Jami",
    c: "75",
    h: "<blockquote>&ldquo;A poet should be so crafty with words that he is envied even for his pains.&rdquo; &mdash; <footer>Criss Jami</footer></blockquote>",
  },
  {
    q: "Our virtues and our failings are inseparable, like force and matter. When they separate, man is no more. ",
    a: "Nikola Tesla",
    c: "105",
    h: "<blockquote>&ldquo;Our virtues and our failings are inseparable, like force and matter. When they separate, man is no more. &rdquo; &mdash; <footer>Nikola Tesla</footer></blockquote>",
  },
  {
    q: "Life does not get better by chance, it gets better by change.",
    a: "Jim Rohn",
    c: "61",
    h: "<blockquote>&ldquo;Life does not get better by chance, it gets better by change.&rdquo; &mdash; <footer>Jim Rohn</footer></blockquote>",
  },
  {
    q: "The final mystery is oneself.",
    a: "Oscar Wilde",
    c: "29",
    h: "<blockquote>&ldquo;The final mystery is oneself.&rdquo; &mdash; <footer>Oscar Wilde</footer></blockquote>",
  },
  {
    q: "Time flies whether you are having fun or not.",
    a: "Mary Engelbreit",
    c: "45",
    h: "<blockquote>&ldquo;Time flies whether you are having fun or not.&rdquo; &mdash; <footer>Mary Engelbreit</footer></blockquote>",
  },
  {
    q: "Whatever we plant in our subconscious mind and nourish with repetition and emotion will one day become reality.",
    a: "Earl Nightingale",
    c: "111",
    h: "<blockquote>&ldquo;Whatever we plant in our subconscious mind and nourish with repetition and emotion will one day become reality.&rdquo; &mdash; <footer>Earl Nightingale</footer></blockquote>",
  },
  {
    q: "Where your talents and the needs of the world cross, there lies your vocation.",
    a: "Aristotle",
    c: "78",
    h: "<blockquote>&ldquo;Where your talents and the needs of the world cross, there lies your vocation.&rdquo; &mdash; <footer>Aristotle</footer></blockquote>",
  },
  {
    q: "We must embrace pain and burn it as fuel for our journey.",
    a: "Kenji Miyazawa",
    c: "57",
    h: "<blockquote>&ldquo;We must embrace pain and burn it as fuel for our journey.&rdquo; &mdash; <footer>Kenji Miyazawa</footer></blockquote>",
  },
  {
    q: "Never let the fear of striking out keep you from playing the game.",
    a: "Babe Ruth",
    c: "66",
    h: "<blockquote>&ldquo;Never let the fear of striking out keep you from playing the game.&rdquo; &mdash; <footer>Babe Ruth</footer></blockquote>",
  },
  {
    q: "Things may come to those who wait, but only the things left by those who hustle.",
    a: "Abraham Lincoln",
    c: "80",
    h: "<blockquote>&ldquo;Things may come to those who wait, but only the things left by those who hustle.&rdquo; &mdash; <footer>Abraham Lincoln</footer></blockquote>",
  },
  {
    q: "Let the beauty of what you love be what you do.",
    a: "Rumi",
    c: "47",
    h: "<blockquote>&ldquo;Let the beauty of what you love be what you do.&rdquo; &mdash; <footer>Rumi</footer></blockquote>",
  },
];
